### ISSUE TITLE
Invalid variable on updateInvoice

### ISSUE THREAD

**Issue by dackers86** [adreyfus-stripe/create-invoice-extension#9]
Hi @adreyfus-stripe 

In the latest version of master, the sendInvoice functions works as expected.

The update function fails as the value of STRIPE_ENDPOINT_SECRET is undefined. 

Extension Parameter show this as STRIPE_WEBHOOK_SECRET. 

Does this need to be updated?

**Comment by adreyfus-stripe** [comment]
Yes good catch! Just fixed: https://github.com/adreyfus-stripe/create-invoice-extension/pull/10
